name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ["1.24.0"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v -o furca-${{ matrix.os }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: furca-${{ matrix.os }}
          path: furca-${{ matrix.os }}*
          retention-days: 7
